sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
script: npm run ci
os:
  - linux
  - osx
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=31b70e6488961b7eb14322b5839b6d9d5169f7bd2ae41d6cce97bc9734400ac8